//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastalarBilgi
    {
        public int HastaNo { get; set; }
        public string HastaAdSoyad { get; set; }
        public string Yas { get; set; }
        public string Adres { get; set; }
        public string Sikayet { get; set; }
    }
}
