//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolikliniklerBilgi
    {
        public int PoliklinikNo { get; set; }
        public string PoliklinikAdi { get; set; }
        public Nullable<int> YatakSayisi { get; set; }
        public Nullable<int> UzmanSayisi { get; set; }
        public string PoliklinikBaskani { get; set; }
        public string PoliklinikBasHemsire { get; set; }
    }
}
